name: kitx_website
description: Website for KitX Project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    community_material_icon: ^5.9.55
    flutter:
        sdk: flutter
    get: ^4.6.6
    loading_animation_widget: ^1.2.1

dev_dependencies:
    flutter_lints: ^3.0.2
    flutter_test:
        sdk: flutter
    flutter_web_optimizer: ^1.4.1

flutter:
    uses-material-design: true

    assets:
        - assets/
