name: Preview Site

on:
    push:
        branches:
            - "dev=main"
    workflow_dispatch:

jobs:
    preview-site:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
            - run: flutter --version
            - name: Enable Flutter Web
              working-directory: kitx_website
              run: flutter config --enable-web
            - name: Download Dependencies
              working-directory: kitx_website
              run: flutter pub get
            - name: Build
              working-directory: kitx_website
              run: flutter build web
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUBTOKEN }}
                publish_dir: ./kitx_website/build/web
                force_orphan: true
                user_name: 'github-ci[bot]'
                user_email: 'github-actions[bot]@users.noreply.github.com'
                commit_message: 'Publish to gh-pages'
