name: Preview Site

on:
    push:
        branches:
            - "dev=main"
        paths:
            - 'KitX Website Flutter/**'
    workflow_dispatch:

jobs:
    preview-site:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
            - run: flutter --version
            - name: Enable Flutter Web
              working-directory: "KitX Website Flutter/kitx_website"
              run: flutter config --enable-web
            - name: Download Dependencies
              working-directory: "KitX Website Flutter/kitx_website"
              run: flutter pub get
            - name: Build
              working-directory: "KitX Website Flutter/kitx_website"
              shell: pwsh
              run: ./build.ps1 -baseHref "/KitX-Website/"
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUBTOKEN }}
                  publish_dir: "./KitX Website Flutter/kitx_website/build/web"
                  force_orphan: true
                  user_name: "github-ci[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
                  commit_message: "Publish to gh-pages"
